name: Docs
on: [push]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install doc dependencies
        run: python -m pip install sphinx sphinx-autoapi
      - name: Build sphinx docs
        run: sphinx-build -WaE --keep-going -b html docs/source/ docs/build/html
      - uses: actions/upload-artifact@v3
        with:
          name: docs-html
          path: docs/build/html/
          retention-days: 7
